export const DELAY = 300
export const DEFAULT_MONTHLY_AMOUNT = 0
export const MINIMUM_LOAN_BALANCE = 1000
export const MAXIMUM_LOAN_BALANCE = 200000
export const MINIMUM_INSTALLMENTS_QUANTITY = 1
export const MAXIMUM_INSTALLMENTS_QUANTITY = 24
